### ISSUE TITLE
QuPath export ROI as OME-XML script crashes

### ISSUE THREAD

**Issue by pwalczysko** [glencoesoftware/ome-omero-roitool#14]
I have followed https://omero-guides.readthedocs.io/en/latest/qupath/docs/qupath.html and then the instructions in the header of this script. See error below. QuPath 0.2.0-m10 on Mac OS. cc @emilroz @jburel @joshmoore 

```
/**
 * -----------------------------------------------------------------------------
 *   Copyright (C) 2019 Glencoe Software, Inc. All rights reserved.
 *
 *
 *   This program is free software; you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation; either version 2 of the License, or
 *   (at your option) any later version.
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details.
 *
 *   You should have received a copy of the GNU General Public License along
 *   with this program; if not, write to the Free Software Foundation, Inc.,
 *   51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * ------------------------------------------------------------------------------
 *
INFO: 170
INFO: ROI type: class qupath.lib.roi.PolygonROI
ERROR: MissingMethodException at line 113: No signature of method: static qupath.lib.gui.prefs.PathPrefs.getColorDefaultAnnotations() is applicable for argument types: () values: []

ERROR: Script error (MissingMethodException)
    at groovy.lang.MetaClassImpl.invokeStaticMissingMethod(MetaClassImpl.java:1568)
    at groovy.lang.MetaClassImpl.invokeStaticMethod(MetaClassImpl.java:1554)
    at org.codehaus.groovy.runtime.callsite.StaticMetaClassSite.call(StaticMetaClassSite.java:50)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:130)
    at Script1.setCommonProperties(Script1.groovy:75)
    at Script1$setCommonProperties.callStatic(Unknown Source)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:55)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:217)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:249)
    at Script1$_run_closure1.doCall(Script1.groovy:174)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.base/java.lang.reflect.Method.invoke(Unknown Source)
    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
    at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1029)
    at groovy.lang.Closure.call(Closure.java:412)
    at org.codehaus.groovy.runtime.DefaultGroovyMethods.eachWithIndex(DefaultGroovyMethods.java:2234)
    at org.codehaus.groovy.runtime.DefaultGroovyMethods.eachWithIndex(DefaultGroovyMethods.java:2214)
    at org.codehaus.groovy.runtime.DefaultGroovyMethods.eachWithIndex(DefaultGroovyMethods.java:2264)
    at org.codehaus.groovy.runtime.dgm$213.invoke(Unknown Source)
    at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:247)
    at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:56)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
    at Script1.run(Script1.groovy:114)
    at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.eval(GroovyScriptEngineImpl.java:317)
    at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.eval(GroovyScriptEngineImpl.java:155)
    at qupath.lib.gui.scripting.DefaultScriptEditor.executeScript(DefaultScriptEditor.java:893)
    at qupath.lib.gui.scripting.DefaultScriptEditor.executeScript(DefaultScriptEditor.java:827)
    at qupath.lib.gui.scripting.DefaultScriptEditor.executeScript(DefaultScriptEditor.java:754)
    at qupath.lib.gui.scripting.DefaultScriptEditor$2.run(DefaultScriptEditor.java:1223)
    at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
    at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.base/java.lang.Thread.run(Unknown Source)


static void setCommonProperties(Shape shape, PathROIObject path, qupath.lib.roi.interfaces.ROI roi) {
    // Set remaining ROI properties
    if (roi.c > -1) {
        shape.setTheC(new NonNegativeInteger(roi.c))
    }
    shape.setTheT(new NonNegativeInteger(roi.t))
    shape.setTheZ(new NonNegativeInteger(roi.z))

    shape.setLocked(path.isLocked())

    // Unpack the color
    def packedColor = path.colorRGB
    if (packedColor == null) {
        if (path.pathClass != null) {
            packedColor = path.pathClass.color
        } else {
            packedColor = PathPrefs.getColorDefaultAnnotations()
        }
    }
    if (packedColor != null) {
        def color = new Color(ColorTools.red(packedColor),
                ColorTools.green(packedColor),
                ColorTools.blue(packedColor),
                ColorTools.alpha(packedColor))
        shape.setStrokeColor(color)
        // Note: QuPath does not allow stroke and fill color to be specified separately
        def overlayOptions = QPEx.currentViewer.getOverlayOptions()
        overlayOptions.getFillAnnotations()
        if ((path.isAnnotation() && overlayOptions.fillAnnotations) ||
                (path.isDetection() && overlayOptions.fillDetections)) {
             shape.setFillColor(color)
        }
    }

    // Note: Not currently used by QuPath, but may be useful for "cutout" ROIs
    shape.setFillRule(FillRule.NONZERO)

    // Note: Currently, QuPath only applies font settings to image labels and scale bars, not ROIs
    // shape.setFontFamily()
    // shape.setFontSize()
    // shape.setFontStyle()

    // Note: QuPath sets stroke thickness as a system-wide property, with one thickness for annotations
    // and another for detections. We'll store the stroke width on each ROI, but when loading an OME-XML
    // the stroke width of last ROI loaded will be used to set the system property.
    if (path.isAnnotation()) {
        shape.setStrokeWidth(new Length(PathPrefs.getThickStrokeThickness(), UNITS.PIXEL))
    } else if (path.isDetection()) {
        shape.setStrokeWidth(new Length(PathPrefs.getThinStrokeThickness(), UNITS.PIXEL))
    }

    // Note: Currently, QuPath does not allow for dashed lines
    // shape.setStrokeDashArray()
}

rois.eachWithIndex { PathROIObject path, int i ->
    def roi = path.getROI()
    print(String.format("ROI type: %s", roi.class))
    def mapAnnotationID = String.format("MapAnnotation-%s", i)
    def shapeID = String.format("Shape:%s", i)
    def roiID = String.format("ROI-%s", i)

    // New ROI
    def omeROI = new ROI()
    omeROI.setID(roiID)
    if (path.pathClass != null) {
        omeROI.setName(path.pathClass.name)
    }

    def union = new Union()

    // Instantiate the class of the shape from the type of ROI and set class specific properties
    switch (roi) {
        case EllipseROI:
            def ellipse = roi as EllipseROI
            def shape = new Ellipse()
            shape.setID(shapeID)
            shape.setX(ellipse.getCentroidX())
            shape.setY(ellipse.getCentroidY())
            shape.setRadiusX(ellipse.getBoundsWidth() / 2)
            shape.setRadiusY(ellipse.getBoundsHeight() / 2)
            setCommonProperties(shape, path, roi)
            union.addShape(shape as Shape)
            break
        case LineROI:
            def line = roi as LineROI
            def shape = new Line()
            shape.setID(shapeID)
            shape.setX1(line.x1)
            shape.setY1(line.y1)
            shape.setX2(line.x2)
            shape.setY2(line.y2)
            // Note: Currently, QuPath does not make use of line endcaps (i.e. arrows)
            // shape.setMarkerStart()
            // shape.setMarkerEnd()
            setCommonProperties(shape, path, roi)
            union.addShape(shape as Shape)
            break
        case PointsROI:
            def points = roi as PointsROI
            points.getPointList().eachWithIndex { point, pointidx ->
                def shape = new Point()
                shape.setID(shapeID + "." + pointidx)
                shape.setX(point.x)
                shape.setY(point.y)
                setCommonProperties(shape, path, roi)
                union.addShape(shape)
            }
            break
        case PolygonROI:
            def polygon = roi as PolygonROI
            def shape = new Polygon()
            def points = polygon.getAllPoints().collect { String.format("%f,%f", it.getX(), it.getY()) }.join(" ")
            shape.setID(shapeID)
            shape.setPoints(points)
            setCommonProperties(shape, path, roi)
            union.addShape(shape)
            break
        case AreaROI:
            def polygon = roi as AreaROI
            def shape = new Polygon()
            def points = polygon.getAllPoints().collect { String.format("%f,%f", it.getX(), it.getY()) }.join(" ")
            shape.setID(shapeID)
            shape.setPoints(points)
            setCommonProperties(shape, path, roi)
            union.addShape(shape)
            break
        case PolylineROI:
            def polyline = roi as PolylineROI
            def shape = new Polyline()
            def points = polyline.getAllPoints().collect { String.format("%f,%f", it.getX(), it.getY()) }.join(" ")
            shape.setID(shapeID)
            shape.setPoints(points)
            setCommonProperties(shape, path, roi)
            union.addShape(shape as Shape)
            break
        case RectangleROI:
            def rect = roi as RectangleROI
            def shape = new Rectangle()
            shape.setID(shapeID)
            shape.setX(rect.x)
            shape.setY(rect.y)
            shape.setWidth(rect.getBoundsWidth())
            shape.setHeight(rect.getBoundsHeight())
            setCommonProperties(shape, path, roi)
            union.addShape(shape as Shape)
            break
        default:
            print("Unsupported ROI type: " + roi)
    }

    if (union.sizeOfShapeList() > 0) {
        omeROI.setUnion(union)
    }

    // Map Annotation
    def mapAnnotation = new MapAnnotation()
    mapAnnotation.setID(mapAnnotationID)

    // Add all the key-value pairs
    def pairList = new ArrayList<MapPair>()
    if (path.pathClass != null) {
        pairList.add(new MapPair("qupath:class", path.pathClass.name))
    }
    if (path.getName()) {
        pairList.add(new MapPair("qupath:name", path.getName()))
    }
    pairList.add(new MapPair("qupath:is-annotation", path.isAnnotation().toString()))
    pairList.add(new MapPair("qupath:is-detection", path.isDetection().toString()))
    path.retrieveMetadataKeys().each {
        pairList.add(new MapPair("qupath:metadata:" + it, path.retrieveMetadataValue(it).toString()))
    }
    mapAnnotation.setValue(pairList)

    // Finalize ROI
    omeROI.linkAnnotation(mapAnnotation)
    ome.addROI(omeROI)
    structuredAnnotations.addMapAnnotation(mapAnnotation)
}

ome.setStructuredAnnotations(structuredAnnotations);

qupath = QPEx.getQuPath()
file = qupath.getDialogHelper().promptToSaveFile("Choose OME-XML export location", null, null, "OME-XML", ".ome.xml")
xmlWriter = new XMLWriter();
xmlWriter.writeFile(file, ome, false);
```

**Comment by melissalinkert** [comment]
That error is due to API changes in QuPath 0.2.0-m9 (https://github.com/qupath/qupath/commit/c3ec8caa4225af850d20115971a60a8115e2e42a#diff-a26d956c33375a9bab6045ddd1fee25c) and 0.2.0-m10 (https://github.com/qupath/qupath/commit/8e8fdbf244265d8540334df46a22408c50283eb2#diff-a26d956c33375a9bab6045ddd1fee25c).  I would expect 0.2.0-m8 to work until we can make a suitable fix.

**Comment by pwalczysko** [comment]
@melissalinkert Indeed, after a lot of back and forth, I can confirm that QuPath 0.2.0-m8 works fine. yes, there are plenty of methods which are simply missing in QuPath 0.2.0-m10 (which is the version I was using in the original report above. Was trying to "quick fix it", but every time I got rid of a method from the script, another error about another missing method appeared. This seems to me like a rather big change of the API between QP 0.2.0-m8 and m9 ?

**Comment by pwalczysko** [comment]
@melissalinkert thank you

**Comment by melissalinkert** [comment]
Proposed fix in https://github.com/glencoesoftware/ome-omero-roitool/pull/15

**Comment by chris-allan** [comment]
Closing now that #15 is merged in.
